USE [Pagebd01]
GO

/****** Object:  Table [dbo].[VENDEDOR]    Script Date: 3/23/2020 4:53:51 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VENDEDOR](
	[CODIGO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NULL,
	[APELLIDO] [nvarchar](50) NULL,
	[NUMERO_IDENTIFICACION] [nvarchar](50) NULL,
	[CODIGO_CIUDAD] [bigint] NULL,
 CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VENDEDOR]  WITH CHECK ADD  CONSTRAINT [FK_VENDEDOR_CIUDAD1] FOREIGN KEY([CODIGO_CIUDAD])
REFERENCES [dbo].[CIUDAD] ([CODIGO])
GO

ALTER TABLE [dbo].[VENDEDOR] CHECK CONSTRAINT [FK_VENDEDOR_CIUDAD1]
GO

